### ISSUE TITLE
`npm test` fails in newer node versions

### ISSUE THREAD

**Issue by mroderick** [jakearchibald/es6-promise#160]
I would like to contribute to this project, but the tests are failing for me in the following node versions.

* 0.12.8
* 0.12.9
* 4.2.4

```
$ npm test

> es6-promise@3.0.2 test /Users/morgan/code/es6-promise
> ember test

version: 0.2.3

A new version of ember-cli is available (1.13.13). To install it, type ember update.
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Built project successfully. Stored in "/Users/morgan/code/es6-promise/tmp/class-tests_dist-90IpqKzG.tmp".
ok 1 Mocha - "./node_modules/.bin/mocha dist/test/browserify.js"

1..1
# tests 1
# pass  1
# fail  0

# ok
/Users/morgan/code/es6-promise/node_modules/ember-cli/node_modules/testem/lib/launcher.js:210
      this.process.kill('SIGKILL')
                  ^
TypeError: Cannot read property 'kill' of null
    at EventEmitter.Launcher.onKillTimeout (/Users/morgan/code/es6-promise/node_modules/ember-cli/node_modules/testem/lib/launcher.js:210:19)
    at Timer.listOnTimeout (timers.js:119:15)
npm ERR! Test failed.  See above for more details.
```

Switching down to node 0.10 allows the tests to run.

Perhaps someone familiar with the test setup could look into ensuring that this can run in newer node versions?

In the meantime, should we update the `README.md` to state that you need to use node 0.10 to contribute to this project?

**Comment by stefanpenner** [comment]
seems to work fine for me with:

```
➜  es6-promise git:(master) npm version
{ 'es6-promise': '3.0.2',
  npm: '3.5.2',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.3.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

**Comment by mroderick** [comment]
That's odd. I'll try again later

**Comment by stefanpenner** [comment]
will reopen if a reproduction can be provided.

**Comment by mroderick** [comment]
Cheers!

**Comment by stefanpenner** [comment]
@mroderick if you find a example, let me know. I'll gladly dig in and see whatsup, but if I can't repro i can't help

**Comment by mroderick** [comment]
I tried again, and am still unable to run the tests in `master`.

```
$ npm version
{ 'es6-promise': '3.0.2',
  npm: '2.14.12',
  ares: '1.10.1-DEV',
  http_parser: '2.5.0',
  icu: '56.1',
  modules: '46',
  node: '4.2.4',
  openssl: '1.0.2e',
  uv: '1.7.5',
  v8: '4.5.103.35',
  zlib: '1.2.8' }
```

If I try to install dependencies under node 5, I get 

```
npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/morgan/.nvm/versions/node/v5.4.0/bin/node" "/Users/morgan/.nvm/versions/node/v5.4.0/bin/npm" "install"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! path /Users/morgan/code/es6-promise/node_modules/ember-cli/node_modules/broccoli/node_modules/handlebars/bin/handlebars
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/morgan/code/es6-promise/node_modules/ember-cli/node_modules/broccoli/node_modules/handlebars/bin/handlebars'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/morgan/code/es6-promise/npm-debug.log
```

```
$ npm version
{ 'es6-promise': '3.0.2',
  npm: '3.3.12',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.4.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

Did you re-install the node modules yesterday?

**Comment by stefanpenner** [comment]
Seems like the cause was a missing phantomjs, docs addressing this have been added
