### ISSUE TITLE
is AIX   supported?

### ISSUE THREAD

**Issue by smartmouse** [jakearchibald/es6-promise#81]
Hello:
I was using node 0.12.x  and AIX- 
bash-4.2$ npm test 
got the following errors.

Thanks in advance/

> es6-promise@2.0.1 test /home/test/es6-promise
> ember test

module.js:338
    throw err;
          ^
Error: Cannot find module 'resolve'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/test/es6-promise/node_modules/.bin/ember:7:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
npm ERR! Test failed.  See above for more details.
-bash-4.2$ npm install
npm WARN package.json broccoli-es3-safe-recast@0.0.8 No README data

> es6-promise@2.0.1 prepublish /home/test/es6-promise
> ember build --environment production

module.js:338
    throw err;
          ^
Error: Cannot find module 'resolve'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/test/es6-promise/node_modules/.bin/ember:7:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! AIX 1
npm ERR! argv "/home/jenkins_nodes/64/bin/node" "/home//jenkins_nodes/64/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! es6-promise@2.0.1 prepublish: `ember build --environment production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es6-promise@2.0.1 prepublish script 'ember build --environment production'.
npm ERR! This is most likely a problem with the es6-promise package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ember build --environment production
npm ERR! You can get their info via:
npm ERR!     npm owner ls es6-promise
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/test/es6-promise/npm-debug.log
-bash-4.2$
-bash-4.2$ node --version
v0.12.0
-bash-4.2$

**Comment by stefanpenner** [comment]
what is AIX ?

**Comment by stefanpenner** [comment]
like IBM AIX ?

**Comment by smartmouse** [comment]
hi , yes

**Comment by stefanpenner** [comment]
if node works, I don't see why the promise implementation wouldn't

**Comment by stefanpenner** [comment]
https://github.com/jakearchibald/es6-promise/pull/82 may have also fixed your ability to build. Although I don't have an AIX machine handy to test..

**Comment by stefanpenner** [comment]
closing this because, I don't think I can reasonably support the build tools on an AIX machine without having some way to test.

If the promise implementation doesn't work, I will gladly reopen.
